spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/movies?useSSL=false
    username: root

  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

s3:
  accessKey: PEHX0GJZ5TBA4XJMVSBC
  secretKey: RNkLbyBojTrxp+umW7Qr0V37MWAKCWaqHZboVL+P
  bucketName: moviefun

logging.level:
  root: WARN
  org.superbiz.moviefun: INFO
  org.superbiz.moviefun.movies: DEBUG